### ISSUE TITLE
Missing requirements, incorrect command, and simply doesn't work.

### ISSUE THREAD

**Issue by Rich700000000000** [RomySaputraSihananda/tiktok-comment-scrapper#8]
1. There are two missing requirements other than just requests: "loguru" and "jmespath", I had to install those before this would work.
2. The "url" flag is now "aweme_id", and the size flag is gone, that needs to be corrected in the readme. 
3. When I try to actually run the code, it crashes with a "NoneType" error:

`2024-12-16 02:18:07.647 | INFO     | __main__:main:38 - start scrap comments 7170139292767882522
Traceback (most recent call last):
  File "/home/david/Packages/tiktok-comment-scrapper/main.py", line 68, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Packages/tiktok-comment-scrapper/main.py", line 42, in main
    comments: Comments = TiktokComment()(
                         ^^^^^^^^^^^^^^^^
  File "/home/david/Packages/tiktok-comment-scrapper/tiktokcomment/tiktokcomment.py", line 161, in __call__
    return self.get_all_comments(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/david/Packages/tiktok-comment-scrapper/tiktokcomment/tiktokcomment.py", line 99, in get_all_comments
    data: Comments = self.get_comments(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/david/Packages/tiktok-comment-scrapper/tiktokcomment/tiktokcomment.py", line 149, in get_comments
    comments=[
             ^
TypeError: 'NoneType' object is not iterable
`

This has been updated to the latest version of python, correct?

**Comment by RomySaputraSihananda** [comment]
I think it's because the aweme_id is invalid, try sending the original link
